#!/usr/bin/env sh

#docker service ps

docker-machine ssh Char "docker service logs $(docker service ps engineering-bay -f "name=engineering-bay.1" -q) --follow"

#docker logs --follow $(docker ps | grep redis |  head -n1 | cut -d " " -f1)